set -g prefix ^B

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U
set -g status-position top

#Theme
set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'janoamaral/tokyo-night-tmux'
# set -g @tokyo-night-tmux_window_id_style 'digital'
# set -g @tokyo-night-tmux_show_music 'off'
# set -g @tokyo-night-tmux_show_path 'on'      # shows current directory
# set -g @tokyo-night-tmux_date_format '%Y-%m-%d %H:%M'
#
# # Style tweaks
# set -g status-left-length 30
# set -g status-right-length 100
# set -g status-position top                     # or bottom, your call

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
setw -g mode-keys vi
set -g mouse on
set-option -g allow-rename off
set-option -g set-titles on
set-option -g set-titles-string "#S"
run -b '~/.tmux/plugins/tpm/tpm'
