[custom]
global\css\disabled_files=@Invalid()
global\css\enabled=true
global\css\preview_map=@Variant(\0\0\0\b\0\0\0\0)
global\js\enabled=false

[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xed\0\0\x2\xe7\0\0\0\0\0\0\0\0\0\0\x4\xed\0\0\x2\xe7\0\0\0\0\0\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x4\xed\0\0\x2\xe7)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4\xee\0\0\x2\xe8\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=true
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[storage-whats]
notification=true
user_agent=Linux Chrome

[system]
DontUseNativeDialog=true
menubar=false
notificationCounter=false
quit_in_close=false
sidebar=false
spellCheckers=false
start_background=true
start_system=true
theme=dark
tray_theme=symbolic_light
wayland=true

[website]
open_page=false
